### ISSUE TITLE
Port to material-ui@next branch

### ISSUE THREAD

**Issue by femski** [STORIS/material-ui-scrollable-tabs#1]
Thank you for this stupendous effort. Most of us on bleeding edge have already moved to @next branch of material-ui. it will be great if efforts like this are based off of @next branch. master branch is not very customizable and @next is great in this regard. Thank you !

**Comment by shawnmcknight** [comment]
Thanks for the compliment!
The roadmap for this project is to create it for the material-ui@next branch.  The goal with that is to have it included in Material-UI proper rather than having it as a separate extension.

**Comment by shawnmcknight** [comment]
PR callemall/material-ui#6502 has been created to roll scrollable behavior into the **@next** branch of material-ui.
The one thing I know that isn't present in that PR which is in this repository is the multi-line font behavior.  However, rather than trying to keep this repo in sync with material-ui, I'm going to put my efforts into improving material-ui proper.  I will work on getting the multi-line font behavior in place once (if?) my PR is approved.
