### ISSUE TITLE
isLargeView solution?

### ISSUE THREAD

**Issue by mgreer** [STORIS/material-ui-scrollable-tabs#4]
Isn't it as simple as...

`const isLargeView = document.documentElement.clientWidth > 500;`

Or are you concerned with SSR?

**Comment by shawnmcknight** [comment]
My biggest concern with `isLargeView` was dealing with viewport size changes in a clean manner.  Setting the value as a constant once would keep the size at whatever the initial viewport width was but an ideal solution would respond to viewport size changes.

I've actually got a solution in place in the `develop` branch which makes use of a utility decorator in the main material-ui library (withWidth.js).  It detects viewport size changes and sends a prop to the `Tabs` component whenever a breakpoint is passed.  The `Tabs` component detects this change, updates the `isLargeView` prop passed to the `Tab` component and the re-rendering cycle is started again.

The biggest challenge here is that the selected tab indicator's size and position is dynamically based on the rendered size of a tab.  If tabs change size then the indicator needs to change along with it.  It's a bit of a chicken-and-egg scenario but I believe I've got a pretty good solution in place on the `develop` branch for it.

To be honest, I haven't ever explored SSR before so I have no idea if this component even works when rendered on the server.  In looking at how withWidth works, it looks like it basically short circuits any potential server side render so I suspect that the develop branch will _work_ but will probably not truly render on the server.  I will have to dig in some more on that when I have some free time to throw at it.

I'm not convinced that the current behavior of the withWidth utility is ideal since the breakpoints used within it seem pretty arbitrary and not in line with the guidelines of material design.  It looks like they've made significant changes to it within the `next` branch so it probably will work better in the next release.

**Comment by mgreer** [comment]
Your solution seems sound, since it will be consistent with the rest of material-ui (even if not perfectly aligned to the specs).I think as long as it short-circuits SSR, its fine. Just don't want it to die (as my solution would).

(BTW, this is a fantastic piece of work, and I found it just as I was beginning work on my own version. Thank you!)
